import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const apercuPro = localFont({
  src: "../public//assets/fonts/ApercuPro-Regular.otf",
  variable: "--apercu"
})
const spectral = localFont({
  src: "../public/assets/fonts/Spectral-Regular.ttf",
  variable: "--spectral"
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${apercuPro.variable} ${spectral.variable} antialiased`}
      >
        <div className="flex flex-col w-screen min-h-screen">
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
